export const ADD_TODO_ACTION = 'ADD_TODO';
export const REMOVE_TODO_ACTION = 'REMOVE_TODO';
export const GET_LOCALSTORAGE_ACTION = 'GET_LOCALSTORAGE'
export const DONE_TODOS_ACTION = 'TOGGLE_TODO'
export const REMOVE_TODOS_ACTION = 'REMOVE_TODO'
export const IMPORTANT_TODOS_ACTION = 'IMPORTANT_TODO'
export const SET_FILTERS = 'SET_FILTERS'
export const SET_SEARCH = 'SET_SEARCH'